apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-demo
  labels:
    environment: staging
    db-schema: v1.4.6
spec:
  replicas: 3
  template:
    metadata:
      labels:
        environment: staging
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause:
            duration: 15s
        - setWeight: 50
        - pause:
            duration: 15s
