apiVersion: promoter.argoproj.io/v1alpha1
kind: ArgoCDCommitStatus
metadata:
  name: argocdcommitstatus-sample
  namespace: default
spec:
  promotionStrategyRef:
    name: argocon-demo
  applicationSelector:
    matchLabels:
      app: demo
  url:
    template: >
      {{- $label := "" -}}
      {{- if eq .Environment "environments/development" -}}
      {{- $label = "development" -}}
      {{- else if eq .Environment "environments/staging" -}}
      {{- $label = "staging" -}}
      {{- else if eq .Environment "environments/production" -}}
      {{- $label = "production" -}}
      {{- end -}}
      {{- printf "%s/applications?labels=environment=%s" "http://localhost:4000" (urlQueryEscape $label) -}}
