apiVersion: promoter.argoproj.io/v1alpha1
kind: DependentsSuccessfulCommitStatus
metadata:
  name: active-checks-dscs
  namespace: default
spec:
  key: dependents-successful
  promotionStrategyRef:
    name: argocon-demo
