apiVersion: promoter.argoproj.io/v1alpha1
kind: GitCommitStatus
metadata:
  name: gitcommitstatus
  namespace: default
spec:
  promotionStrategyRef:
    name: argocon-demo
  key: revert-check
  description: "Non-promoter changes on running environment"
  # This expression returns false if ANY of these conditions are true:
  # 1. Commit subject starts with "Revert" → fail
  # 2. Commit body starts with "Revert" → fail
  # 3. Commit has a "Git-commit-status: pending" trailer → fail
  # The validation passes only if NONE of these conditions are true
  expression: '!(Commit.Subject startsWith "Revert" || Commit.Body startsWith "Revert" || ("Git-commit-status" in Commit.Trailers && Commit.Trailers["Git-commit-status"][0] == "pending"))'

