apiVersion: promoter.argoproj.io/v1alpha1
kind: GitRepository
metadata:
  labels:
    app.kubernetes.io/name: promoter
    app.kubernetes.io/managed-by: kustomize
  name: argocon-demo
  namespace: default
spec:
  github:
    owner: zachaller
    name: argocon-gitops-promoter-hydrate-demo
  scmProviderRef:
    name: scmprovider-sample
