apiVersion: promoter.argoproj.io/v1alpha1
kind: CommitStatus
metadata:
  annotations:
    hcapActive: "false"
  labels:
    promoter.argoproj.io/commit-status: hcap
  name: hcap
  namespace: default
spec:
  description: HCAP check for production
  gitRepositoryRef:
    name: argocon-demo
  name: production/hcap
  sha: "8cdb04d1853d4e812259d59753f30d4aff6421d6"
  url: https://example.com
