apiVersion: promoter.argoproj.io/v1alpha1
kind: PromotionStrategy
metadata:
  annotations:
  name: argocon-demo
  namespace: default
spec:
  checks:
  - key: argocd-health
  - key: yaml-lint
  environments:
    - branch: environments/development
    - branch: environments/staging
      checks:
      - key: performance-test
    - branch: environments/production
      checks:
      - key: deployment-freeze
  gitRepositoryRef:
    name: argocon-demo
