apiVersion: promoter.argoproj.io/v1alpha1
kind: WebRequestCommitStatus
metadata:
  name: change-management-approval
  namespace: default
spec:
  promotionStrategyRef:
    name: argocon-demo
  key: change-management-approval
  descriptionTemplate: "Check for approved change records in current time window"
  reportOn: proposed
  httpRequest:
    urlTemplate: "http://localhost:8987/v1/change-management-service/changes/search?asset_id=6772992770778240&status=APPROVED&limit=25"
    method: GET
    timeout: 30s
    headerTemplates:
      Accept: application/json
  expression: |
    Response.StatusCode == 200 &&
    len(Response.Body.change_records) > 0 &&
    any(Response.Body.change_records, {
      date(#.change_request.start_time) <= now() &&
      date(#.change_request.end_time) >= now()
    })
  mode:
    trigger:
      requeueDuration: 5m
      expression: |
        // Environment refers to the CURRENT environment being processed (e.g., prod1 or prod2)
        // Each environment is processed independently by the controller
        
        // Check if there's an open PR for THIS environment
        // Note: string() conversion needed because PullRequestState is a Go type alias
        let hasOpenPR = Environment.PullRequest != nil && 
                        string(Environment.PullRequest.State) == "open";
        
        // Check if THIS environment's commit status (key: "change-management") already shows success
        // Environment.Proposed.CommitStatuses contains commit statuses for THIS environment only
        // This is populated from CommitStatus resources by the ChangeTransferPolicy controller
        // When the dry SHA changes, new CommitStatus starts as pending, so we'll poll again
        // Note: string() conversion needed because CommitStatusPhase is a Go type alias
        let alreadySucceeded = any(Environment.Proposed.CommitStatuses ?? [], 
                                   {.Key == "change-management" && string(#.Phase) == "success"});
        
        // Poll if:
        // 1. THIS environment has an open PR
        // 2. AND THIS environment hasn't succeeded yet for this SHA
        hasOpenPR && !alreadySucceeded
