apiVersion: promoter.argoproj.io/v1alpha1
kind: WebRequestCommitStatus
metadata:
  name: change-management-approval
  namespace: default
spec:
  promotionStrategyRef:
    name: argocon-demo
  key: change-management-approval
  descriptionTemplate: "Check for approved change records in current time window"
  reportOn: proposed
  httpRequest:
    urlTemplate: "http://localhost:8987/v1/change-management-service/changes/search?asset_id=1372489579564901493&status=CLOSED_SUCCESS&limit=25&commit_id={{ .Environment.Proposed.Dry.Sha }}"
    method: GET
    timeout: 30s
    headerTemplates:
      Accept: application/json
  expression: |
    Response.StatusCode == 200 &&
    len(Response.Body.change_records) > 0 &&
    any(Response.Body.change_records, {
      date(#.change_request.start_time) <= now() &&
      date(#.change_request.end_time) >= now()
    })
  mode:
    trigger:
      requeueDuration: 30s
      expression: |
        // Track dry SHA state to handle no-op hydrations
        let currentDrySha = Environment.Proposed.Dry.Sha;
        let storedSuccessfulDrySha = ExpressionData.lastSuccessfulDrySha ?? "";
        let storedAttemptedDrySha = ExpressionData.lastAttemptedDrySha ?? "";

        let hasOpenPR = Environment.PullRequest != nil &&
                        string(Environment.PullRequest.State) == "open";

        // Check if CommitStatuses show success (may be stale from previous dry SHA)
        let currentPhaseIsSuccess = any(Environment.Proposed.CommitStatuses ?? [],
                                        {.Key == "change-management-approval" && string(#.Phase) == "success"});

        // Only mark as successful if we attempted THIS dry SHA and now see success
        let newSuccessfulSha = (currentPhaseIsSuccess && storedAttemptedDrySha == currentDrySha) 
                               ? currentDrySha 
                               : storedSuccessfulDrySha;

        // Have we succeeded for THIS specific dry SHA?
        let alreadySucceededForThisSha = newSuccessfulSha == currentDrySha;

        // Trigger if PR is open AND we haven't succeeded for this dry SHA
        let shouldTrigger = hasOpenPR && !alreadySucceededForThisSha;

        // Return object with trigger decision and state to persist
        {
          trigger: shouldTrigger,
          lastSuccessfulDrySha: newSuccessfulSha,
          lastAttemptedDrySha: shouldTrigger ? currentDrySha : storedAttemptedDrySha
        }
