apiVersion: promoter.argoproj.io/v1alpha1
kind: WebRequestCommitStatus
metadata:
  name: change-management-approval
  namespace: default
spec:
  promotionStrategyRef:
    name: argocon-demo
  key: change-management-approval
  description: "Check for approved change records in current time window"
  reportOn: proposed
  polling:
    interval: 1m
  httpRequest:
    url: "http://localhost:8987/v1/change-management-service/changes/search?asset_id=6272405973343114011&status=APPROVED&limit=25"
    method: GET
    timeout: 30s
    headers:
      Accept: application/json
  expression: |
    Response.StatusCode == 200 &&
    len(Response.Body.change_records) > 0 &&
    any(Response.Body.change_records, {
      date(#.change_request.start_time) <= now() &&
      date(#.change_request.end_time) >= now()
    })
