apiVersion: promoter.argoproj.io/v1alpha1
kind: WebRequestCommitStatus
metadata:
  name: change-management-approval
  namespace: default
  labels:
    test: test1
spec:
  promotionStrategyRef:
    name: argocon-demo
  key: change-management-approval
  descriptionTemplate: "Check for approved change records in current time window"
  reportOn: proposed
  httpRequest:
    urlTemplate: "http://localhost:8987/v1/change-management-service/changes/search?asset_id=1372489579564901493&status=CLOSED_SUCCESS&limit=25&commit_id={{ .Environment.Proposed.Dry.Sha }}"
    method: GET
    timeout: 30s
    headerTemplates:
      Accept: application/json
  expression: |
    Response.StatusCode == 200 &&
    len(Response.Body.change_records) > 0 &&
    any(Response.Body.change_records, {
      date(#.change_request.start_time) <= now() &&
      date(#.change_request.end_time) >= now()
    })
  mode:
    trigger:
      requeueDuration: 30s
      expression: |
          // Use Note.DrySha from git note - this is authoritative and updates even for no-op hydrations
          let currentDrySha = Environment.Proposed.Note.DrySha;
          let storedSuccessfulDrySha = ExpressionData.lastSuccessfulDrySha ?? "";

          let hasOpenPR = Environment.PullRequest != nil &&
                          string(Environment.PullRequest.State) == "open";

          // Check CommitStatuses for success
          let currentPhaseIsSuccess = any(Environment.Proposed.CommitStatuses ?? [],
                                          {.Key == "change-management-approval" && string(#.Phase) == "success"});

          // If we see success and current dry SHA matches what we're tracking, record it
          let newSuccessfulSha = currentPhaseIsSuccess ? currentDrySha : storedSuccessfulDrySha;

          // Have we succeeded for THIS specific dry SHA (from git note)?
          let alreadySucceededForThisSha = newSuccessfulSha == currentDrySha && currentDrySha != "";

          let shouldTrigger = hasOpenPR && !alreadySucceededForThisSha;

          {
            trigger: shouldTrigger,
            lastSuccessfulDrySha: newSuccessfulSha
          }
