apiVersion: promoter.argoproj.io/v1alpha1
kind: WebRequestCommitStatus
metadata:
  name: change-management-approval
  namespace: default
  labels:
    test: test2
spec:
  promotionStrategyRef:
    name: argocon-demo
  key: change-management-approval
  descriptionTemplate: "Check for approved change records in current time window"
  reportOn: proposed
  httpRequest:
    urlTemplate: "http://localhost:8987/v1/change-management-service/changes/search?asset_id=1372489579564901493&status=CLOSED_SUCCESS&limit=25&commit_id={{ .Environment.Proposed.Dry.Sha }}"
    method: GET
    timeout: 30s
    headerTemplates:
      Accept: application/json
  expression: |
    Response.StatusCode == 200 &&
    len(Response.Body.change_records) > 0 &&
    any(Response.Body.change_records, {
      date(#.change_request.start_time) <= now() &&
      date(#.change_request.end_time) >= now()
    })
  mode:
    trigger:
      requeueDuration: 30s
      expression: |
          // Use Note.DrySha from git note - this is authoritative and updates even for no-op hydrations
          let currentDrySha = Environment.Proposed.Note.DrySha;
          let storedSuccessfulDrySha = ExpressionData.lastSuccessfulDrySha ?? "";

          let hasOpenPR = Environment.PullRequest != nil &&
                          string(Environment.PullRequest.State) == "open";

          // Check CommitStatuses for success
          let currentPhaseIsSuccess = any(Environment.Proposed.CommitStatuses ?? [],
                                          {.Key == "change-management-approval" && string(#.Phase) == "success"});

          // If we see success and current dry SHA matches what we're tracking, record it
          let newSuccessfulSha = currentPhaseIsSuccess ? currentDrySha : storedSuccessfulDrySha;

          // Have we succeeded for THIS specific dry SHA (from git note)?
          let alreadySucceededForThisSha = newSuccessfulSha == currentDrySha && currentDrySha != "";

          let shouldTrigger = hasOpenPR && !alreadySucceededForThisSha;

          {
            trigger: shouldTrigger,
            lastSuccessfulDrySha: newSuccessfulSha
          }

---

apiVersion: promoter.argoproj.io/v1alpha1
kind: WebRequestCommitStatus
metadata:
  name: change-management-open
  namespace: default
spec:
  descriptionTemplate: Open change request for dry SHA
  key: change-management-open
  reportOn: proposed
  promotionStrategyRef:
    name: argocon-demo
  
  httpRequest:
    method: POST
    timeout: 30s
    urlTemplate: http://localhost:8987/v1/change-management-service/change
    headerTemplates:
      Content-Type: application/json
      Accept: application/json
    bodyTemplate: |
      {
        "asset_id": "1372489579564901493",
        "on_behalf_of": "gitops-promoter",
        "short_description": "Deploy commit {{ .Environment.Proposed.Dry.Sha }} to {{ .Environment.Branch }} via automated pipeline",
        "description": "Automated deployment of commit {{ .Environment.Proposed.Dry.Sha }} to {{ .Environment.Branch }} for asset 1372489579564901493. Standard deployment following approved change management procedures and best practices for proper change tracking.",
        "environment": "staging",
        "backout_plan": "Rollback to previous version by redeploying previous commit using automated rollback procedure and validation",
        "change_plan": "Standard change roll out using automated deployment pipeline and infrastructure as code with monitoring",
        "test_plan": "Pre-deployment testing completed in lower environments with automated test suite validation and verification",
        "category": "Application",
        "sub_category": "Release",
        "commit_id": "{{ .Environment.Proposed.Dry.Sha }}",
        "start_time": "{{ now }}",
        "end_time": "{{ now }}",
        "risk": "low",
        "repo_url": "https://github.intuit.com/your-org/your-repo"
      }
  
  expression: |
    Response.StatusCode == 200 &&
    has(Response.Body.id) &&
    Response.Body.id != ""
  
  mode:
    trigger:
      requeueDuration: 30s
      expression: |
        // Get current dry SHA
        let currentDrySha = Environment.Proposed.Dry.Sha;
        
        // Get the last SHA we opened a change for
        let lastOpenedSha = ExpressionData.lastOpenedSha ?? "";
        
        // Check if we've already opened a change for this SHA
        let alreadyOpened = lastOpenedSha == currentDrySha;
        
        // Check if there's an open PR
        let hasOpenPR = Environment.PullRequest != nil &&
                        string(Environment.PullRequest.State) == "open";
        
        // Trigger only if PR is open and we haven't opened for this SHA
        let shouldTrigger = hasOpenPR && !alreadyOpened;
        
        // Return trigger decision and persist the SHA
        {
          trigger: shouldTrigger,
          lastOpenedSha: shouldTrigger ? currentDrySha : lastOpenedSha
        }
