apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: development:/Namespace:/development
  name: development
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: development:/Service:development/canary-demo
    version: v1.0.138
  name: canary-demo
  namespace: development
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: canary-demo
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: development:/Service:development/canary-demo-preview
    version: v1.0.138
  name: canary-demo-preview
  namespace: development
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: canary-demo
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: development:argoproj.io/Rollout:development/canary-demo
    version: v1.0.138
  labels:
    environment: development
  name: canary-demo
  namespace: development
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: canary-demo
  strategy:
    canary:
      canaryService: canary-demo-preview
      steps:
        - setWeight: 20
        - pause:
            duration: 5
        - setWeight: 80
        - pause:
            duration: 5
  template:
    metadata:
      annotations:
        version: v1.0.138
      labels:
        app: canary-demo
        environment: development
    spec:
      containers:
        - image: argoproj/rollouts-demo:red
          imagePullPolicy: Always
          name: canary-demo
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 5m
              memory: 32Mi
