apiVersion: promoter.argoproj.io/v1alpha1
kind: ScmProvider
metadata:
  annotations:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: promoter
  name: scmprovider-sample
  namespace: argocd
spec:
  github: {}
  secretRef:
    name: my-auth-promotion
