apiVersion: promoter.argoproj.io/v1alpha1
kind: PromotionStrategy
metadata:
  annotations:
  name: argocon-demo
  namespace: default
spec:
  activeCommitStatuses:
  - key: healthy
  environments:
  - branch: environments/development
    autoMerge: false
  - branch: environments/staging
  - branch: environments/production
    proposedCommitStatuses:
    - key: hcap
  gitRepositoryRef:
    name: argocon-demo
