apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promotion-strategy
  namespace: argocd
spec:
  ignoreDifferences:
  - group: promoter.argoproj.io
    kind: CommitStatus
    jsonPointers:
    - /spec/sha
    - /metadata/annotations/hcapActive
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: user-configuration/promotion-app
    repoURL: https://github.com/zachaller/argocon-gitops-promoter-hydrate-demo
    targetRevision: HEAD
