apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-demo
  labels:
    environment: production
    db-schema: v1.15
spec:
  replicas: 2
  template:
    metadata:
      labels:
        environment: production
