apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-demo
  labels:
    environment: development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        environment: development
  strategy:
    canary:
      steps:
        - setWeight: 100
