apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: production-use2
  name: production-use2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: production-use2
    version: v1.0.8
  name: canary-demo
  namespace: production-use2
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: canary-demo
    version: v1.0.8
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: production-use2
    version: v1.0.8
  name: canary-demo-preview
  namespace: production-use2
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: canary-demo
    version: v1.0.8
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app.kubernetes.io/instance: production-use2
    db-schema: v1.2
    environment: production
    version: v1.0.8
  name: canary-demo
  namespace: production-use2
spec:
  replicas: 3
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: canary-demo
      version: v1.0.8
  strategy:
    canary:
      canaryService: canary-demo-preview
      steps:
        - setWeight: 20
        - pause:
            duration: 5
        - setWeight: 80
        - pause:
            duration: 5
  template:
    metadata:
      labels:
        app: canary-demo
        environment: production
        version: v1.0.8
    spec:
      containers:
        - image: argoproj/rollouts-demo:green
          imagePullPolicy: Always
          name: canary-demo
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 5m
              memory: 32Mi
